### ISSUE TITLE
Fix the cache logic

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#1]
Allow more than one user to be working on images from the same phase but not be annotating the exact same images.

Task complexity: Medium to Low

Solution: Add add’l checked out flag which is set when image enters the work queue

Potential issues: Need to every once in a while “clear” the flag in case someone stops working on an image and doesn’t submit it

ADD TO Metadata model:    
image_checked_out = Boolean
image_checkout_time = TIMESTAMP  #So can set cron job to put images back in the work pool

**Comment by iwhitford** [comment]
We saw this behavior again today when pulling up images in phase 2 that two different users can be working on the same image at the same time.

**Comment by brianhelba** [comment]
Mostly fixed by getting a random image in phase 1, and no longer applies to phase 2.
