### ISSUE TITLE
CSS Flexbox causes momentary resize problems

### ISSUE THREAD

**Issue by alex-r-bigelow** [ImageMarkup/isic-archive#107]
The gallery view's SVG element queries its parent to determine how bit it should be—and the flexbox CSS style looks at how big the SVG element is. Consequently, a resize event looks like this:

- Gallery JS code : resize SVG
- CSS Flex box : adjust page

--- resize event ---
- CSS Flex box : adjust page    <--- at this point, the SVG element is its old size
- Gallery JS code: resize SVG

**Comment by brianhelba** [comment]
Seems to be gone now.
