### ISSUE TITLE
Convert header to a bootstrap navbar, then add menu groupings

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#108]
The menu should have something like the hierarchy:
- `ISIC Archive` (brand name style, clickable to go Home)
- `About` (but a better title for this would be nice)
  - `Home`
  - `About`
  - `Working Group Members` (renamed from `Members`)
  - `Forum`
- `Lesion Images`
  - `Upload Dataset` (if permission)
  - `Lesion Images`
- `Annotation Study Results`
  - `Featuresets`
  - `Manage Annotation Studies` (use pen icon, renamed from `Annotation Studies`)
  - `Annotation Study Results` (use eye icon)
- `Your Tasks` (if logged in)

**Comment by aadikalloo** [comment]
Forum should probably be its own button. Otherwise looks good

**Comment by brianhelba** [comment]
@aadikalloo I agree we want to make the Forum more prominent eventually, but since it needs some work to populate it with content and links back to the ISIC Archive, I wanted to put it in a less conspicuous place. Once we start thinking about the 2017 Challenge, we will certainly do that work and bump the button to the top level.

Of course, if we get negative feedback about this, we can move it sooner.
