### ISSUE TITLE
Make original filenames visible to dataset contributor

### ISSUE THREAD

**Issue by aadikalloo** [ImageMarkup/isic-archive#212]
Currently all original filenames are hidden. Not sure if it is too complex to have each dataset contributor see original filenames for only their own datasets. If it is, just give Aadi access to original filenames for now. Still want original filenames hidden from public.

**Comment by msmolens** [comment]
Is this satisfied by https://github.com/ImageMarkup/isic-archive/pull/296?

**Comment by brianhelba** [comment]
Yes. They're visible to just the dataset reviewers, but it provides the functionality that @aadikalloo needs. Closing.
