### ISSUE TITLE
Phase 2 zoom

### ISSUE THREAD

**Issue by iwhitford** [ImageMarkup/isic-archive#22]
The zoom used for image annotation in phase 2 is too high for images of small lesions causing pixellation and loss of detail presented to the user.

**Comment by brianhelba** [comment]
![image6](https://cloud.githubusercontent.com/assets/1282879/10543701/70aa42be-73ed-11e5-9c5b-40c4c294993a.jpeg)

**Comment by brianhelba** [comment]
Phase 2 always presents images as fully zoomed out. #31 will fix zoom issues entirely.
