### ISSUE TITLE
Tooltips get stuck on image gallery

### ISSUE THREAD

**Issue by msmolens** [ImageMarkup/isic-archive#251]
On the image gallery image thumbnail tooltips can get stuck. This happens intermittently for me, but seems to be triggered easily by rapidly clicking images.

Browser: Chrome, Firefox

![image](https://cloud.githubusercontent.com/assets/7122091/19703548/25b8f450-9ad2-11e6-840f-df47310069a6.png)

**Comment by brianhelba** [comment]
This is happening even after the tooltip rendering performance improvement in https://github.com/ImageMarkup/isic-archive/pull/240/commits/df4a2c1008e35337412d2f8da03af57ddadfee5d
