### ISSUE TITLE
Console errors on study results page

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#258]
Whenever switching between tabs (after a study and image have been selected), I get
```
TypeError: Cannot read property 'getElementsByTagName' of null(…)     onloadwff.js:1569
```

**Comment by msmolens** [comment]
Does it happen if you disable browser extensions? `onloadwff.js` looks to be part of LastPass.

**Comment by brianhelba** [comment]
Indeed, it's a problem with my extension. I didn't bother to Google it before reporting. 

Closing this.
