### ISSUE TITLE
Automatically logged out

### ISSUE THREAD

**Issue by aadikalloo** [ImageMarkup/isic-archive#34]
When logging into a new browser or new computer for the first time, users get logged out automatically from ISIC. Occurs when logging in with password (not google, although haven't tested with google). 

Especially tends to happen when logging in, then clicking on Image Tasks, then clicking on the Back button to go back to the ISIC homepage. 

Using Chrome on Windows 7 currently.

**Comment by brianhelba** [comment]
Updated Girder. Let's see if it continues to happen.

**Comment by brianhelba** [comment]
Cannot reproduce.
