### ISSUE TITLE
Validate metadata for melanoma

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#457]
Add 4 new validators for `clinical` metadata:
* `mel_thick_mm`
  * values are coded as float, and can be in the CSV as anything like:
    * `1.23 mm`
    * `1.23mm`
    * `1.23`
    * `1`
  * this may be in the CSV as `mel_thick` alternatively
* `mel_class`
  * values:
    * `"melanoma in situ"`
    * `"invasive melanoma"`
    * `"recurrent/persistent melanoma, in situ"` (comma is optional in CSV)
    * `"recurrent/persistent melanoma, invasive"` (comma is optional in CSV)
    * `"melanoma nos"`
* `ulcer`
  * boolean value
* `mel_type`
  * values:
    * `"superficial spreading"` (alias `"ssm"`)
    * `"nodular"`
    * `"lentigo maligna melanoma"` (alias `"lmm"`)
    * `"acral lentiginous melanoma"` (alias `"alm"`)
    * `"NOS"`
    * `"spindle cell features"`
    * `null` (alias `"unknown"`)

All can still take CSV values of `"unknown"`, coded as `None`.

Finally, add an inter-field validation rule whereby if any of these are set to non-`None` values, then `diagnosis` must be exactly `"melanoma"`.

**Comment by kallooa** [comment]
@brianhelba why do mel_class values look like that?

**Comment by brianhelba** [comment]
@kallooa Sorry, posted this prematurely, I'm still editing it.

**Comment by brianhelba** [comment]
Done editing the main issue.

**Comment by brianhelba** [comment]
Just updated this issue with new values for `mel_type`.

**Comment by msmolens** [comment]
@kallooa Can you suggest human-readable names for these fields to be used in faceted search? 
e.g. `clin_size_long_diam_mm` -> "Clinical Size - Longest Diameter (mm)"

**Comment by kallooa** [comment]
@msmolens That seems appropriate to me

**Comment by msmolens** [comment]
@kallooa Sorry, that was just an example of the type of name we need. How about names for the following fields:
 - `mel_thick_mm`
- `mel_class`
- `ulcer`
- `mel_type`

**Comment by brianhelba** [comment]
I'll defer to @kallooa for these.
