### ISSUE TITLE
mail_utils.sendEmail should gracefully fail when "to" is empty

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#491]
In some cases (when first creating an empty instance), emails can be sent "to" an empty list of users (e.g. if there are no 'Dataset Contributor' admins). In this case, the `mail_utils.sendEmail` function should not fail (as it does now).

**Comment by msmolens** [comment]
@brianhelba `mail_utils.sendEmail` is actually part of Girder: https://github.com/girder/girder/blob/14d5b2154545bcb60b7211bb7d2b5eb2c94e6537/girder/utility/mail_utils.py#L73

It seems reasonable for a `sendEmail` function to indicate an error when no email addresses are provided. What do you think about handling this locally? We could catch the exception or by guard the function call with a check that the list isn't empty. I believe the only place this is necessary is the case mentioned in the issue:
https://github.com/ImageMarkup/isic-archive/blob/1a7e11a10df5c613f257da150d9bff9481950342/server/api/user.py#L118

**Comment by brianhelba** [comment]
Yes, that sounds reasonable. I wasn't sure how many places like this there were when I reported the issue, but just skipping the email if the group is empty should be fine.
