### ISSUE TITLE
girder restart issue

### ISSUE THREAD

**Issue by jettmcp** [ImageMarkup/isic-archive#649]
Ansible is failing at the girder restart after mongodb restart and running handler [girder : wait_for]. This times out.

Issue seems to be with the mail_utils.py where traceback error is 
from girder.constants import 'SettingKey'
ImportError: cannot import name 'SettingKey'

I can't get past this.

**Comment by jettmcp** [comment]
Thanks - that fixed that problem. I got past that but then crashed at Create asset store.

Ansible output:
fatal: [web]: FAILED! => changed=false 
  msg: |-
    <class 'girder_client.HttpError'>:HTTP error 403: GET http://localhost:8080/api/v1/assetstore
    Response text: {"message": "Administrator access required.", "type": "access"}
    {"message": "Administrator access required.", "type": "access"}
    Traceback (most recent call last):
      File "/tmp/ansible_girder_payload_8_dfgn6q/__main__.py", line 1831, in main
        gcm(module)
      File "/tmp/ansible_girder_payload_8_dfgn6q/__main__.py", line 1106, in __call__
        self.__process(method)
      File "/tmp/ansible_girder_payload_8_dfgn6q/__main__.py", line 1134, in __process
        ret = getattr(self, method)(*args, **kwargs)
      File "/tmp/ansible_girder_payload_8_dfgn6q/__main__.py", line 1663, in assetstore
        assetstores = {a['name']: a for a in self.get("assetstore")}
      File "/usr/local/lib/python3.6/dist-packages/girder_client/__init__.py", line 503, in get
        return self.sendRestRequest('GET', path, parameters, jsonResp=jsonResp)
      File "/usr/local/lib/python3.6/dist-packages/girder_client/__init__.py", line 497, in sendRestRequest
        response=result)
    girder_client.HttpError: HTTP error 403: GET http://localhost:8080/api/v1/assetstore
    Response text: {"message": "Administrator access required.", "type": "access"}

PLAY RECAP *********************************************************************
web                        : ok=50   changed=41   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

Monday 24 June 2019  19:23:32 +0000 (0:00:00.724)       0:10:39.940 *********** 
=============================================================================== 
girder : command ------------------------------------------------------- 97.42s
large_image : Install vips --------------------------------------------- 75.91s
isic : Build ISIC Admin GUI -------------------------------------------- 75.83s
isic : Install ISIC GUI dependencies ----------------------------------- 73.83s
isic : Build ISIC Integration GUI -------------------------------------- 63.32s
isic : apt ------------------------------------------------------------- 49.71s
isic : Install isic-archive package ------------------------------------ 34.70s
python : Install virtualenv dependencies ------------------------------- 30.18s
girder : Install Python package ---------------------------------------- 15.66s
nodejs : Upgrade npm --------------------------------------------------- 11.48s
girder : wait_for ------------------------------------------------------- 9.81s
nodejs : Install package ------------------------------------------------ 9.10s
girder.mongodb : Install MongoDB package -------------------------------- 8.32s
girder : Install build dependencies ------------------------------------- 7.53s
isic : Install package dependencies ------------------------------------- 6.83s
large_image : Install tiff tile source system dependencies -------------- 6.61s
nodejs : Add PPA -------------------------------------------------------- 6.60s
girder.mongodb : Add MongoDB PPA ---------------------------------------- 6.42s
large_image : Install large_image --------------------------------------- 5.71s
large_image : Install pil tile source system dependencies --------------- 4.66s
Playbook run took 0 days, 0 hours, 10 minutes, 39 seconds
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Here is the journalctl -f -u girder output

Jun 24 19:21:41 isic-archive systemd[1]: Started Girder.
Jun 24 19:21:43 isic-archive systemd[1]: Stopping Girder...
Jun 24 19:21:43 isic-archive systemd[1]: Stopped Girder.
Jun 24 19:21:43 isic-archive systemd[1]: Started Girder.
Jun 24 19:21:44 isic-archive girder[24701]: Running in mode: development
Jun 24 19:21:45 isic-archive girder[24701]: Connecting to MongoDB: mongodb://localhost:27017/girder
Jun 24 19:21:51 isic-archive girder[24701]: Loaded plugin "jobs"
Jun 24 19:21:51 isic-archive girder[24701]: Loaded plugin "worker"
Jun 24 19:21:51 isic-archive girder[24701]: Loaded tile source tiff
Jun 24 19:21:51 isic-archive girder[24701]: Loaded plugin "large_image"
Jun 24 19:21:51 isic-archive girder[24701]: Loaded plugin "gravatar"
Jun 24 19:21:52 isic-archive girder[24701]: WARNING: No description docs present for route GET redirects/uploadBatch
Jun 24 19:21:52 isic-archive girder[24701]: WARNING: No description docs present for route GET redirects/literature
Jun 24 19:21:52 isic-archive girder[24701]: WARNING: No description docs present for route GET redirects/registerMetadata
Jun 24 19:21:52 isic-archive girder[24701]: WARNING: No description docs present for route GET redirects/applyMetadata
Jun 24 19:21:52 isic-archive girder[24701]: Loaded plugin "isic_archive"
Jun 24 19:21:52 isic-archive girder[24701]: [24/Jun/2019:19:21:52] ENGINE Bus STARTING
Jun 24 19:21:52 isic-archive girder[24701]: Started asynchronous event manager thread.
Jun 24 19:21:52 isic-archive girder[24701]: CherryPy Checker:
Jun 24 19:21:52 isic-archive girder[24701]: '/home/vagrant/env/share/girder/static' (root + dir) is not an existing filesystem path.
Jun 24 19:21:52 isic-archive girder[24701]: section: [/]
Jun 24 19:21:52 isic-archive girder[24701]: root: None
Jun 24 19:21:52 isic-archive girder[24701]: dir: '/home/vagrant/env/share/girder/static'
Jun 24 19:21:52 isic-archive girder[24701]: [24/Jun/2019:19:21:52] ENGINE Started monitor thread '_TimeoutMonitor'.
Jun 24 19:21:52 isic-archive girder[24701]: [24/Jun/2019:19:21:52] ENGINE Started monitor thread 'Autoreloader'.
Jun 24 19:21:52 isic-archive girder[24701]: [24/Jun/2019:19:21:52] ENGINE Serving on http://127.0.0.1:8080
Jun 24 19:21:52 isic-archive girder[24701]: [24/Jun/2019:19:21:52] ENGINE Bus STARTED
Jun 24 19:23:31 isic-archive girder[24701]: 127.0.0.1 - - [24/Jun/2019:19:23:31] "GET /api/v1/user/authentication HTTP/1.1" 401 46 "" "python-requests/2.18.4"
Jun 24 19:23:31 isic-archive girder[24701]: 127.0.0.1 - - [24/Jun/2019:19:23:31] "POST /api/v1/user?login=admin&firstName=Provision&lastName=Admin&password=password&email=provision.admin%40isic-archive.com&admin=true HTTP/1.1" 200 744 "" "python-requests/2.18.4"
Jun 24 19:23:32 isic-archive girder[24701]: 127.0.0.1 - - [24/Jun/2019:19:23:32] "GET /api/v1/user/authentication HTTP/1.1" 200 814 "" "python-requests/2.18.4"
Jun 24 19:23:32 isic-archive girder[24701]: 127.0.0.1 - - [24/Jun/2019:19:23:32] "GET /api/v1/assetstore HTTP/1.1" 403 63 "" "python-requests/2.18.4"

**Comment by jettmcp** [comment]
If there any other logs or output I can provide please let me know. I am not sure what is the most relevant to send you. - Thanks

**Comment by danlamanna** [comment]
Follow up issue is in #654
