### ISSUE TITLE
Make all POST endpoints for the ISIC HTTP API accept JSON or form encoding

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#66]
JSON-encoded data is available via `self.getBodyJson()`, whereas form-encoded data is in the `params` argument. The request's `Content-Type` header should be used to determine which to use, with the default being form-encoded.

**Comment by msmolens** [comment]
@brianhelba Can you review https://github.com/ImageMarkup/isic-archive/pull/65/commits/fd877432497a37aef3a43665036bb76860d24c0d before I proceed on this issue? Also see comment: https://github.com/ImageMarkup/isic-archive/pull/65#discussion-diff-67208479

**Comment by brianhelba** [comment]
Fixed by `IsicResource._decodeParams`.
