### ISSUE TITLE
Add tooltips with diagnosis info to Phase 0 gallery

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#71]
@aadikalloo Let me know what field names we should display by default. The current list is here: https://github.com/ImageMarkup/isic-archive/blob/master/custom/static/js/image-review.js#L45

I'd hope we have enough control over the CSV files to make these fields names case-sensitive, but we could make it match more loosely if necessary.

**Comment by aadikalloo** [comment]
pathologist report = 'pathology'
cleaned diagnoses = 'diagnosis data'

**Comment by aadikalloo** [comment]
benign_malignant

**Comment by brianhelba** [comment]
Fixed.
