### ISSUE TITLE
.dev TLD causes error in Chrome

### ISSUE THREAD

**Issue by msmolens** [ImageMarkup/isic-archive#81]
Using `.dev` as the TLD for the hostname in the Vagrantfile causes conflicts now that `.dev` is a real gTLD (generic top-level domain): https://www.iana.org/domains/root/db/dev.html. Accessing `isic-archive.dev` in Chrome gives an `ERR_ICANN_NAME_COLLISION` error.

Renaming the hostname to `isic-archive.devel` would resolve the issue, or perhaps there is another best practice.

**Comment by brianhelba** [comment]
@msmolens @ronichoudhury I'd like to fix this by changing the test server to use `isic-archive.devel`, but you'll have to manually update your `/etc/hosts` file and reprovision (or edit the Nginx config file) afterwards.

Let me know when you're prepared to do so, and I merge a fix.

**Comment by msmolens** [comment]
@brianhelba My environment already uses `isic-archive.devel`, so any time is good.
