### ISSUE TITLE
Vagrant private network fails on Windows

### ISSUE THREAD

**Issue by msmolens** [ImageMarkup/isic-archive#82]
Running `vagrant up` on Windows gives an error when setting up the private network (i.e. host-only networking in VirtualBox):

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aInterfaceName.isEmpty()] at 'F:\tinderbox\win-rel\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in long __cdecl HostNetworkInterface::init(class com::Bstr,class com::Bstr,class com::Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0038).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 71 of file VBoxManageHostonly.cpp
```

Even though it's possible to work around this error by a series of manual steps, accessing the VM from the host at port 80 never works.

A workaround is to:
- disable the private network in the Vagrantfile
- port forward localhost:8080 to VM:80
- Add the following to `%SystemRoot%\System32\drivers\etc\hosts`:

> 127.0.0.1 isic-archive.dev
> 127.0.0.1 isic-archive.upstream

Then you can access isic-archive.dev and isic-archive.upstream at port 8080.

**Comment by brianhelba** [comment]
@msmolens Thanks for the detailed report.

**Comment by brianhelba** [comment]
I'll try to resolve this by getting rid of the private network interface.
