### ISSUE TITLE
node.js install fails

### ISSUE THREAD

**Issue by msmolens** [ImageMarkup/isic-archive#95]
Installing node.js now fails when running `vagrant up` for the first time:

    TASK [nodesource.node : Install Node.js] ***************************************
    fatal: [default]: FAILED! => {
        "cache_update_time": 1471379270,
        "cache_updated": true,
        "changed": false,
        "failed": true,
        "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\" install 'nodejs=4.4*'' failed: E: Version '4.4*' for 'nodejs' was not found\n",
        "stderr": "E: Version '4.4*' for 'nodejs' was not found\n",
        "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n",
        "stdout_lines": [
            "Reading package lists...",
            "Building dependency tree...",
            "Reading state information..."
        ]
    }

Bumping `nodejs_version` in `ansible/roles/girder/meta/main.yml` to `4.5` fixes the error, but it's interesting that 4.4 would no longer be available.

**Comment by brianhelba** [comment]
Should be fixed now.
